name: Rails test with Doppler

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@359bebbc29cbe6c87da6bc9ea3bc930432750108
        with:
          ruby-version: '2.7.5'
      - name: Set up Doppler
        run: make setup-doppler-project
      - name: Install dependencies
        run: bin/bundle install
      - name: Run tests
        run: make test